FROM node:10.13-alpine
ENV http_proxy http://alca.proxy.corp.sopra:8080/ 
ENV https_proxy http://alca.proxy.corp.sopra:8080/
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY package*.json ./
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production -g @angular/cli
RUN npm install --production --silent
COPY . .
EXPOSE 4200
CMD ng serve --host 0.0.0.0